project:
  type: website
  output-dir: docs

website:
  title: "MGTA495 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hw1_questions.qmd
        text: HW1
      - href: hw2_questions.qmd
        text: HW2
      - href: hw3_blueprinty.qmd
        text: HW3
      - href: hw4_questions.qmd
        text: HW4
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
